services:
  test-viajero-api:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - viajero_data:/app/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viajero.rule=Host(`viajero-api.joaquinvasquez.com`)"
      - "traefik.http.routers.viajero.entrypoints=websecure"
      - "traefik.http.routers.viajero.tls.certresolver=cloudflare"
      - "traefik.http.services.viajero.loadbalancer.server.port=8080"
    restart: unless-stopped

volumes:
  viajero_data:

networks:
  web:
    external: true
